version: "3.3"


services:
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    container_name: backend
    build: ./backend
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - static_value:/usr/src/app/static/
      - media_value:/usr/src/app/media/
    environment:
      - DEBUG=${DEBUG}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DOMAIN=${DOMAIN}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - API_KEY=${API_KEY}
      - API_NAME=${API_NAME}
      - ADMIN_URL=${ADMIN_URL}
      - EMAIL=${EMAIL}
      - EMAIL_TOKEN=${EMAIL_TOKEN}
      - CELERY_BROKER=${CELERY_BROKER}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TARGET_CHAT_ID=${TARGET_CHAT_ID}
      - CSRF_TRUSTED_DOMAINS=${CSRF_TRUSTED_DOMAINS}
    depends_on:
      postgres:
        condition: service_healthy


  redis:
    image: redis:latest
    container_name: redis


  celery:
    container_name: celery
    build: ./backend
    user: nobody
    depends_on:
      - backend
      - redis
      - postgres
    volumes:
      - ./backend:/usr/src/app
      - static_value:/usr/src/app/static/
      - media_value:/usr/src/app/media/
    environment:
      - DEBUG=${DEBUG}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DOMAIN=${DOMAIN}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - API_KEY=${API_KEY}
      - API_NAME=${API_NAME}
      - ADMIN_URL=${ADMIN_URL}
      - EMAIL=${EMAIL}
      - EMAIL_TOKEN=${EMAIL_TOKEN}
      - CELERY_BROKER=${CELERY_BROKER}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TARGET_CHAT_ID=${TARGET_CHAT_ID}
      - CSRF_TRUSTED_DOMAINS=${CSRF_TRUSTED_DOMAINS}


  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    links:
      - backend:backend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_value:/usr/src/app/static
      - media_value:/usr/src/app/media


volumes:
  postgresql-data:
  static_value:
  media_value:
