version: '3.6'

x-backend_environment: &backend_environment
  environment:
    - DEBUG=False
    - SECRET_KEY=secrettestkey
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_HOST=postgres
    - DB_PORT=5432

services:
  postgres:
    image: postgres:14.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    restart: unless-stopped

  backend:
    restart: unless-stopped
    command: sh -c "/tmp/entrypoint.test.sh"
    <<: *backend_environment
    depends_on:
      - postgres
      - redis
    volumes:
      - ./test_media:/usr/src/app/media

  celery_send_mails:
    build: ./backend
    restart: unless-stopped
    command: celery -A config worker -l error -E -c 2
    <<: *backend_environment
    depends_on:
      - backend
      - redis
    volumes:
      - ./test_media:/usr/src/app/media

  celery_send_many_mails:
    build: ./backend
    restart: unless-stopped
    command: celery -A config worker -l error -E -c 2
    <<: *backend_environment
    depends_on:
      - backend
      - redis
    volumes:
      - ./test_media:/usr/src/app/media

  nginx:
    restart: unless-stopped
    volumes:
      - ./test_media:/usr/src/app/media

  tgbot:
    restart: unless-stopped
    volumes:
      - ./test_media:/usr/src/app/media