version: "3.3"


services:
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  pgbackups:
    container_name: backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_EXTRA_OPTS=-Z9 -E UTF-8 --schema=public --blobs
      - SCHEDULE=@weekly
      - BACKUP_KEEP_DAYS=2
      - BACKUP_KEEP_WEEKS=2
      - BACKUP_KEEP_MONTHS=2


  backend:
    container_name: backend
    build: ./backend
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - static_value:/usr/src/app/static/
      - media_value:/usr/src/app/media/
    environment:
      - DEBUG=${DEBUG}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DOMAIN=${DOMAIN}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - API_KEY=${API_KEY}
      - API_NAME=${API_NAME}
      - ADMIN_URL=${ADMIN_URL}
      - EMAIL=${EMAIL}
      - EMAIL_TOKEN=${EMAIL_TOKEN}
      - CELERY_BROKER=${CELERY_BROKER}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TARGET_CHAT_ID=${TARGET_CHAT_ID}
      - CSRF_TRUSTED_DOMAINS=${CSRF_TRUSTED_DOMAINS}
      - SENTRY_DNS=${SENTRY_DNS}
      - DNS=${DNS}
      - ALLOWED_CHATS=${ALLOWED_CHATS}
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c /tmp/entrypoint.sh


  redis:
    image: redis:latest
    container_name: redis
    depends_on:
      - postgres
    restart: always


  celery:
    container_name: celery
    build: ./backend
    user: nobody
    depends_on:
      - backend
      - redis
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - static_value:/usr/src/app/static/
      - media_value:/usr/src/app/media/
    environment:
      - DEBUG=${DEBUG}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DOMAIN=${DOMAIN}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - API_KEY=${API_KEY}
      - API_NAME=${API_NAME}
      - ADMIN_URL=${ADMIN_URL}
      - EMAIL=${EMAIL}
      - EMAIL_TOKEN=${EMAIL_TOKEN}
      - CELERY_BROKER=${CELERY_BROKER}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TARGET_CHAT_ID=${TARGET_CHAT_ID}
      - CSRF_TRUSTED_DOMAINS=${CSRF_TRUSTED_DOMAINS}
      - SENTRY_DNS=${SENTRY_DNS}
      - DNS=${DNS}
      - ALLOWED_CHATS=${ALLOWED_CHATS}
    command: celery -A config worker -l error -c 2


  tgbot:
    container_name: tgbot
    build: ./backend
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - static_value:/usr/src/app/static/
      - media_value:/usr/src/app/media/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEBUG=${DEBUG}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DOMAIN=${DOMAIN}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - API_KEY=${API_KEY}
      - API_NAME=${API_NAME}
      - ADMIN_URL=${ADMIN_URL}
      - EMAIL=${EMAIL}
      - EMAIL_TOKEN=${EMAIL_TOKEN}
      - CELERY_BROKER=${CELERY_BROKER}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TARGET_CHAT_ID=${TARGET_CHAT_ID}
      - CSRF_TRUSTED_DOMAINS=${CSRF_TRUSTED_DOMAINS}
      - SENTRY_DNS=${SENTRY_DNS}
      - DNS=${DNS}
      - ALLOWED_CHATS=${ALLOWED_CHATS}
    depends_on:
      - backend
      - postgres
    command: sh -c 'uvicorn apps.tgbot.fastapp:app --host 0.0.0.0 --port 5555 --reload & python -m apps.tgbot.main'
    ports:
      - "5555:5555"


  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    links:
      - backend:backend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_value:/usr/src/app/static
      - media_value:/usr/src/app/media


volumes:
  postgresql-data:
  static_value:
  media_value:


networks:
  my_network:
    driver: bridge