lint.select = ["E4", "E7", "E9", "F", "B", "Q", "I"]
lint.ignore = [
    "ANN101",
    "RUF001",
    "S101",
    "TID252",
    "D102",
    "D100",
    "RUF002",
    "ANN001",
    "ANN201",
    "A003",
    "RUF012",
    "D106",
    "D101",
    "W191",
    "ERA001",
    "ANN002",
    "ANN003",
    "Q000",
    "Q003",
    "D206",
    "COM812",
    "D203",
    "E731",
    "B904",
    "B007",
    "E712",
    "E711",
    "E501",
    "B008",
    "B006",
    "B020",
    "B018",
    "F722",
    "F405",
    "F403",
    "B026",
    "E402",
]
src = ["."]
fix = true
fixable = ["I001"]
lint.ignore-init-module-imports = true
target-version = "py310"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "**/migrations/**",
    "__init__.py",
    "apps.py",
    "fabfile.py",
    "response.py",
    "frontend",
    "static",
    "media",
    ".js",
    "cli",
    "**/tests/**",
    "**/management/**",
]

# Same as Black.
line-length = 100
# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[lint.isort]
length-sort = true
lines-after-imports = 2
lines-between-types = 1
known-local-folder = ["apps"]

[lint.isort.sections]
"django" = ["django"]
"apps" = ["apps"]

[format]
quote-style = "single"
docstring-code-format = true
docstring-code-line-length = 100

[lint.pycodestyle]
max-doc-length = 100
max-line-length = 100
